/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6/samples
 */

plugins {
    java
    application
    id("com.diffplug.spotless").version("6.18.0")
}

allprojects {

    repositories {
        mavenCentral()
    }

    apply(plugin = "java")
    apply(plugin = "com.diffplug.spotless")
    apply(plugin = "application")


    dependencies {
        val jacksonVer = "2.14.2"
        implementation("com.fasterxml.jackson.core:jackson-databind:${jacksonVer}")
        implementation("com.fasterxml.jackson.datatype:jackson-datatype-jdk8:${jacksonVer}")
        implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jacksonVer}")
        testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")
    }
    tasks.getByName<Test>("test") {
        useJUnitPlatform()
    }

    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }

    spotless {
        java {
            googleJavaFormat().aosp()
        }
    }

}

