/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.6/userguide/multi_project_builds.html
 */

rootProject.name = "csi01__csc330__s23__18731__class-collab"

include("class-exercise")
//include("week3")
//include("week5-class")
//include("week6-properties")
//include("week7-inheritance")
//include("week7-unit-test")
//include("week8-abstraction")
//include("week8-lambda")
//include("week10-text-persist")
//include("week13-persist-2")
include("week13-2-menu-item")