
###

GET http://localhost:8080/order/0

###

PUT http://localhost:8080/order/0/accept

###
POST http://localhost:8080/order?storeId=d6eadcaa-c490-7bbb-2418-b3d49dfd5b1f

soda pizza

###


WEBSOCKET ws://localhost:8080/drive

####

WEBSOCKET ws://localhost:8080/store

1.pizza 2.wing
####

WEBSOCKET ws://localhost:8080/admin

get

###
