http://localhost:8080/food/0

###

POST http://localhost:8080/food

pepperoni

###
PUT http://localhost:8080/food

pepperoni


###

GET http://localhost:8080/order/0

###

PUT http://localhost:8080/order/0/accept

###
POST http://localhost:8080/order?storeId=0bc57cd8-5a50-4a06-364b-81d5c308aa41

1.pizza 2 .wing
###


WEBSOCKET ws://localhost:8080/drive

####

WEBSOCKET ws://localhost:8080/store


####

