http://localhost:8080/food/0

###

POST http://localhost:8080/food

pepperoni

###
PUT http://localhost:8080/food

pepperoni


###

GET http://localhost:8080/store/menus

###

PUT http://localhost:8080/food/joe/menu

1.pizza

###


WEBSOCKET ws://localhost:8080/driver

####

WEBSOCKET ws://localhost:8080/store


####
